name = "COPT"
uuid = "227a2e2d-e949-4d8e-a1da-7384fe6f0b9f"
repo = "https://github.com/COPT-Public/COPT.jl"
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
MathOptInterface = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
